In [2]:
import numpy as np
import pandas as pd

## Perceptron Algorithim

In [76]:

y = np.array([1,1,-1])
b = 0
i = 0
dataset = pd.read_csv("exoplanets.csv")
x = np.hstack(
        [
            dataset.drop(["exoplanet"], axis=1).to_numpy(),
        ]
    )

k,theta = 0, np.matrix(np.zeros(x.shape[1]))
y = dataset["exoplanet"].to_numpy().astype(np.int64)
theta

matrix([[0., 0.]])

In [83]:


while i < y.size:
    if np.any((np.dot(theta[k],x[i]) * y[i] + b)<=0):
        
        for j in range(y.size):
            if np.any(np.dot(theta[k],x[j]) * y[j] + b <=0):
                
                theta = np.insert(theta, k+1,(theta[k] + (y[j] * x[j])), axis=0)
                b += y[j]
                k+=1
                print(theta[k],b, x[j])
        i = -1
    i+=1
theta[3].dot(x[1]) + 1

matrix([[-281.2317]])

In [3]:
(0.322*np.array([-1.9,0])) -0.497*np.array([0.5,0.75]) + 0.175*np.array([1.6,-2.5])

array([-0.5803 , -0.81025])

# Regression


In [10]:
x = np.array([[2,1],[-4,-2],[-2,-1]])
y = np.array([3,-3,-1])
i = np.array([[1,0],[0,1]])
theta = np.zeros(2)
theta
i

array([[1, 0],
       [0, 1]])

In [20]:
print(np.linalg.inv(i + (np.matmul(x.T,x))))


# for i in range(3):
#     theta = theta + (y[i] - theta.dot(x[i])) * x[i]
# theta

[[ 0.22580645 -0.38709677]
 [-0.38709677  0.80645161]]


# Decision Trees

In [3]:
temp = np.array([10,20,15,15,15,20,25,25,10])
alt = np.array([0,0,1,1,0,0,0,1,0])
din = np.array([False,True,True,True,False,True,True,False,False])

In [22]:
m = 0
stop = 0
for j in range(10,25):
    n = 0
    for i in range(9):
        if (temp[i] > 15) == din [i]:
            n+=1
    if n/9 > m:
        m = n/9
        stop = j
m, stop

(0.4444444444444444, 10)

In [20]:
for j in range(10,25):
    n = 0
    for i in range(9):
        if (temp[i] > j) == din [i]:
            n+=1
        if n/9 == m:
            print(j)

10
11
12
13
14


In [8]:
n = 0
for i in range(9):
    if alt[i] == din[i]:
        n+=1
n/9

0.5555555555555556